- flare/component.py
- flare/handle_resp.py
- flare/typedefs.py
- pyproject.toml
> Add param spec

- README.md
- flare/__init__.py
- flare/component.py
- flare/context.py
- flare/converters.py
- flare/exceptions.py
- flare/handle_resp.py
- flare/id.py
- pyproject.toml
This allows things to be converted to and from a string
> Add Converters

- .github/workflows/ci.yml
- .github/workflows/tests.yml
- flare/__init__.py
- flare/component.py
- flare/context.py
- flare/converters.py
- flare/handle_resp.py
- flare/serde.py
- noxfile.py
- pyproject.toml
- tests/flare/test_converters.py
> add workflows

- flare/converters.py
- flare/internal/serde.py
> Fix 0 not being escaped 

- flare/context.py
- flare/internal/event_handler.py
Implement the Context object derived from the implementation in `miru`.
Closes #14
> Implement Context

- flare/__init__.py
- flare/component.py
- flare/components/__init__.py
- flare/components/base.py
- flare/components/button.py
- flare/components/select.py
- flare/converters.py
- flare/internal/serde.py
- flare/row.py
> Add select menus

- flare/components/button.py
- flare/components/select.py
> Fix button label & emoji not being optional

- flare/converters.py
> Fix deserializing Unions

- flare/converters.py
> Add BoolConverter

- .github/workflows/ci.yml
> Typechecking CI no longer runs lint pipeline

- flare/components/base.py
> Fix args not working

- flare/converters.py
> Use latin1 as encoding

- flare/converters.py
> Make supporting subclasses for type in converters explicit

- flare/components/base.py
Hash default cookie with `blake2s` to reduce size to 8 chars.
Closes #37
> Hash default cookie

- flare/internal/serde.py
> Change default value of SEP and NULL

- flare/converters.py
> Speed up fetching converters with `lru_cache`

- docs/source/guides/converters.md
> Add converter guide

- README.md
- docs/source/getting-started.md
- docs/source/guides/converters.md
- flare/components/base.py
- flare/context.py
- flare/converters.py
- flare/internal/bootstrap.py
- flare/internal/event_handler.py
- flare/internal/serde.py
- flare/row.py
Add async converters
This PR makes it so all `flare.Row`s must be awaited. Examples are updated to reflect this.
> Async Converters

- .github/workflows/ci.yml
- .github/workflows/tests.yml
- flare/converters.py
- flare/internal/bootstrap.py
> Fix CI not running on PRs

- requirements.txt
> Bump hikari version to dev112

- flare/dataclass.py
> Fix a bug where dataclasses would have wrong default value

- examples/basic.py
- flare/context.py
Title, I know its bad to combine them in the same PR but I was extremely lazy :point_right::point_left:
> Add an example for components and `ctx.values`

- pyproject.toml
> Improve project metadata

- examples/basic.py
- flare/components/base.py
- flare/components/button.py
- flare/components/select.py
- flare/row.py
- pyproject.toml
> Support hikari dev113

- pyproject.toml
> Prepare for release 0.1.0b1

- .github/workflows/docs.yml
- noxfile.py
- pyproject.toml
> Fix the CI

- flare/internal/event_handler.py
- flare/internal/serde.py
Oops... Type ignore killed me
This PR updates typing to work better as well
> Fix bug that stopped components from working

- pyproject.toml
> Prepare for release 0.1.0b2

- flare/components/select.py
Allow select menu to use hikar.SelectMenuOption for options.  This also allows the capability for select menu options to have descriptions as well
> Add hikari.SelectMenuOption Capability

- README.md
- examples/basic.py
Attempt to add clarity to the README and docs
> Improve README and docs

- README.md
- docs/source/guides/modal.md
> Add missing awaits in docs

- flare/components/base.py
- flare/components/functional.py
- pyproject.toml
Bump sigparse and hikari. Messy PR but whatever.
> Bump Depedencies

- flare/components/base.py
- flare/components/select.py
- add set_channels
- add set_channel_types function
> Add `set_channel_types` function

- flare/context/base.py
> Fix Context not allowing for proper deffering

- flare/converters.py
- flare/internal/serde.py
- noxfile.py
- pyproject.toml
> prepare 0.1.0

- .github/workflows/publish.yml
Reverts brazier-dev/hikari-flare#109
> Revert "twine --skip-existing in publish workflow"

- flare/components/modal.py
https://github.com/brazier-dev/hikari-flare/issues/112
> Fix modal text inputs always required
